/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sirefa;

import classpackage.Empleado;
import classpackage.Roles;
import dialogPackageLuis.dlgEmpleadosPrincipal;
import dialogspackage.dlgLogin;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.event.MenuEvent;

/**
 *
 * @author ClaudioPaz
 */
public class frm_VentanaPrincipal extends javax.swing.JFrame implements ActionListener{
    /**
     * Creates new form frm_VentanaPrincipal
     */
    
    private Empleado empleado;
    
    /*Menú para administración*/
    private JMenu menuAdministracion;
    private JMenuItem subMenuUsuarios;
    
    /*Menú para doctores*/
    private JMenu menuDoctores;
    
    /*Menú para pacientes*/
    private JMenu menuPacientes;
    
    /*Menú para farmacia*/
    private JMenu menuFarmacia;
    private JMenuItem subMenuInventarioDeMedicamentos;
    
    public frm_VentanaPrincipal() 
    {
        initComponents();
        
        //Maximizar pantalla
        this.setSize(this.getMaximumSize().width, this.getMaximumSize().height);
        
        this.empleado = new Empleado();
        
        this.inicializarMenus();
    }
    
    private void inicializarMenus()
    {
        Empleado empleado = this.empleado;
        
        //Menu y submenús para doctores
        this.menuDoctores = new JMenu();
        this.menuDoctores.setText("Doctores");
        
        //Menú y submenús para administradores
        this.subMenuUsuarios = new JMenuItem();
        this.subMenuUsuarios.setText("Gestión de empleados"); 
        
        this.menuAdministracion = new JMenu();
        this.menuAdministracion.setText("Administración");
        
        this.menuAdministracion.add(this.subMenuUsuarios);
        
        this.subMenuUsuarios.addActionListener(this);
        
        
        
        this.menuPacientes = new JMenu();
        this.menuPacientes.setText("Pacientes");
        
        //Menús y submenús para farmacia
        this.menuFarmacia = new JMenu();
        this.menuFarmacia.setText("Farmacia");
        
        this.subMenuInventarioDeMedicamentos = new JMenuItem();
        this.subMenuInventarioDeMedicamentos.setText("Inventario de farmacia");  
        
        this.menuFarmacia.add(this.subMenuInventarioDeMedicamentos);
        this.subMenuInventarioDeMedicamentos.addActionListener(this);
    }
    
    @Override
    public void actionPerformed(ActionEvent e) 
    {
        JMenuItem menu = (JMenuItem)e.getSource();
        
        switch(menu.getText())
        {
            case "Gestión de empleados":
            {
                dlgEmpleadosPrincipal dialogo = new dlgEmpleadosPrincipal(this, true);
                dialogo.setLocationRelativeTo(this);
                
                dialogo.setVisible(true);
                break;
            }    
        }
    }
    
    public void showLogin()
    {
        dlgLogin dialogo = new dlgLogin(this, true, this.empleado);
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
        
        this.crearMenu();
    }
    
    /*
        Menú que se crea en base a los roles del usuario que
        acaba de iniciar sesión.
    */
    private void crearMenu()
    {
        this.empleado.getEmpleadoDB().obtenerRoles();
        
        for(Roles rol : this.empleado.getIdRol())
        {
            switch(rol.getNombre())
            {
                case "Medico":
                {
                    this.menuPrincipal.add(this.menuDoctores);                    
                    this.menuPrincipal.add(this.menuPacientes);    
                    break;
                }
                case "Administrador de sistema":
                {
                    this.menuPrincipal.add(this.menuAdministracion);
                }
                case "Inventario":
                {
                    this.menuPrincipal.add(this.menuFarmacia);
                    break;
                }
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        menuPrincipal = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        subMenuCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        menuInicio.setText("Inicio");

        subMenuCerrarSesion.setText("Salir");
        subMenuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCerrarSesionActionPerformed(evt);
            }
        });
        menuInicio.add(subMenuCerrarSesion);

        menuPrincipal.add(menuInicio);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.showLogin();
    }//GEN-LAST:event_formWindowOpened

    private void subMenuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCerrarSesionActionPerformed
        
    }//GEN-LAST:event_subMenuCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenuItem subMenuCerrarSesion;
    // End of variables declaration//GEN-END:variables
}
