-- MySQL Script generated by MySQL Workbench
-- 03/28/15 14:36:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SIREFA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SIREFA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SIREFA` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
USE `SIREFA` ;

-- -----------------------------------------------------
-- Table `SIREFA`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIREFA`.`Persona`;
CREATE TABLE IF NOT EXISTS `SIREFA`.`Persona` (
  `idPersona`  INT NOT NULL AUTO_INCREMENT,
  `primerNombre` VARCHAR(45) NOT NULL,
  `segundoNombre` VARCHAR(45) NULL,
  `primerApellido` VARCHAR(45) NOT NULL,
  `segundoApellido` VARCHAR(45) NULL,
  `fechaDeNacimiento` DATE NOT NULL,
  `direccion` VARCHAR(200) NULL,
  `numeroTelefono` VARCHAR(50) NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIREFA`.`Tipo_Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIREFA`.`Tipo_Empleado`;
CREATE TABLE IF NOT EXISTS `SIREFA`.`Tipo_Empleado` (
  `idTipo_Empleado` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipo_Empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIREFA`.`Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIREFA`.`Empleado`;
CREATE TABLE IF NOT EXISTS `SIREFA`.`Empleado` (
  `idPersona` INT NOT NULL,
  `nombreDeUsuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `fechaIngreso` DATE NOT NULL,
  `idTipoEmpleado` INT NOT NULL,
  PRIMARY KEY (`idPersona`),
  INDEX `FK_EMPLEADO_PERSONA` (`idPersona` ASC),
  INDEX `FK_TipoEmpleado_idx` (`idTipoEmpleado` ASC),
  CONSTRAINT `FK_Persona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `SIREFA`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TipoEmpleado`
    FOREIGN KEY (`idTipoEmpleado`)
    REFERENCES `SIREFA`.`Tipo_Empleado` (`idTipo_Empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIREFA`.`Paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIREFA`.`Paciente`;
CREATE TABLE IF NOT EXISTS `SIREFA`.`Paciente` (
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idPersona`),
  INDEX `FK_Persona_idx` (`idPersona` ASC),
  CONSTRAINT `FK_PACIENTE_PERSONA`
    FOREIGN KEY (`idPersona`)
    REFERENCES `SIREFA`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIREFA`.`Cita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIREFA`.`Cita`;
CREATE TABLE IF NOT EXISTS `SIREFA`.`Cita` (
  `idCita` INT NOT NULL AUTO_INCREMENT,
  `idPersona` INT NOT NULL,
  `idEmpleado` INT NOT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`idCita`),
  INDEX `FK_Paciente_idx` (`idPersona` ASC),
  INDEX `FK_Empleado_idx` (`idEmpleado` ASC),
  CONSTRAINT `FK_CITA_PACIENTE`
    FOREIGN KEY (`idPersona`)
    REFERENCES `SIREFA`.`Paciente` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CITA_EMPLEADO`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `SIREFA`.`Empleado` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIREFA`.`Info_PreClinica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIREFA`.`Info_PreClinica`;
CREATE TABLE IF NOT EXISTS `SIREFA`.`Info_PreClinica` (
  `idCita` INT NOT NULL,
  `idPreClinica` INT NOT NULL AUTO_INCREMENT,
  `PA` VARCHAR(45) NULL,
  `P_FC` VARCHAR(45) NULL,
  `temperatura` VARCHAR(45) NULL,
  `FR` VARCHAR(45) NULL,
  `peso` FLOAT NULL,
  `talla` FLOAT NULL,
  `cabeza` VARCHAR(45) NULL,
  `ojos` VARCHAR(45) NULL,
  `nariz` VARCHAR(45) NULL,
  `boca` VARCHAR(45) NULL,
  `oidos` VARCHAR(45) NULL,
  `garganta` VARCHAR(45) NULL,
  `cuello` VARCHAR(45) NULL,
  `torax` VARCHAR(45) NULL,
  `mamas` VARCHAR(45) NULL,
  `corazon` VARCHAR(45) NULL,
  `pulmones` VARCHAR(45) NULL,
  `abdomen` VARCHAR(45) NULL,
  `genitales` VARCHAR(45) NULL,
  `piel_faneras` VARCHAR(45) NULL,
  `neurologico` VARCHAR(45) NULL,
  PRIMARY KEY (`idPreClinica`),
  INDEX `FK_Cita_idx` (`idCita`),
  CONSTRAINT `FK_Cita`
    FOREIGN KEY (`idCita`)
    REFERENCES `SIREFA`.`Cita` (`idCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIREFA`.`Remitencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIREFA`.`Remitencia`;
CREATE TABLE IF NOT EXISTS `SIREFA`.`Remitencia` (
  `idRemitencia` INT NOT NULL AUTO_INCREMENT,
  `idCita` INT NOT NULL,
  `hospital` VARCHAR(45) NOT NULL,
  `nombreDoctor` VARCHAR(45) NULL,
  PRIMARY KEY (`idRemitencia`),
  INDEX `FK_Cita_idx` (`idCita` ASC),
  CONSTRAINT `FK_REMITENCIA_CITA`
    FOREIGN KEY (`idCita`)
    REFERENCES `SIREFA`.`Cita` (`idCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIREFA`.`Prescripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS  `SIREFA`.`Prescripcion`;
CREATE TABLE IF NOT EXISTS `SIREFA`.`Prescripcion` (
  `idPrescripcion` INT NOT NULL AUTO_INCREMENT,
  `idCita` INT NOT NULL,
  `observacion` VARCHAR(200) NULL,
  `otros` VARCHAR(45) NULL,
  PRIMARY KEY (`idPrescripcion`),
  INDEX `FK_Cita_idx` (`idCita` ASC),
  CONSTRAINT `FK_PRESCRIPCION_CITA`
    FOREIGN KEY (`idCita`)
    REFERENCES `SIREFA`.`Cita` (`idCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIREFA`.`Tipo_Medicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS  `SIREFA`.`Tipo_Medicamento`;
CREATE TABLE IF NOT EXISTS `SIREFA`.`Tipo_Medicamento` (
  `idTipo_Medicamento` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo_Medicamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIREFA`.`Medicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIREFA`.`Medicamento`;
CREATE TABLE IF NOT EXISTS `SIREFA`.`Medicamento` (
  `idMedicamento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `idCategoria` INT NULL,
  `idTipoMedicamento` INT NOT NULL,
  PRIMARY KEY (`idMedicamento`),
  INDEX `FK_TipoMedicamento_idx` (`idTipoMedicamento` ASC),
  CONSTRAINT `FK_TipoMedicamento`
    FOREIGN KEY (`idTipoMedicamento`)
    REFERENCES `SIREFA`.`Tipo_Medicamento` (`idTipo_Medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIREFA`.`Medicamento_Instancia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIREFA`.`Medicamento_Instancia`;
CREATE TABLE IF NOT EXISTS `SIREFA`.`Medicamento_Instancia` (
  `idMedicamento_Instancia` INT NOT NULL AUTO_INCREMENT,
  `idMedicamento` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `fechaIngreso` DATE NOT NULL,
  `fechaVencimiento` DATE NOT NULL,
  PRIMARY KEY (`idMedicamento_Instancia`),
  INDEX `FK_Medicamento_idx` (`idMedicamento` ASC),
  CONSTRAINT `FK_Medicamento`
    FOREIGN KEY (`idMedicamento`)
    REFERENCES `SIREFA`.`Medicamento` (`idMedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIREFA`.`Medicamento_Prescripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIREFA`.`Medicamento_Prescripcion`;
CREATE TABLE IF NOT EXISTS `SIREFA`.`Medicamento_Prescripcion` (
  `idMedicamento` INT NOT NULL,
  `idPrescripcion` INT NOT NULL,
  `cantidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idMedicamento`, `idPrescripcion`),
  INDEX `FK_Medicamento_idx` (`idMedicamento` ASC),
  INDEX `FK_Prescripcion_idx` (`idPrescripcion` ASC),
  CONSTRAINT `FK_MEDICAMENTO_PRESCRIPCION_MEDICAMENTO`
    FOREIGN KEY (`idMedicamento`)
    REFERENCES `SIREFA`.`Medicamento` (`idMedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MEDICAMENTO_PRESCRIPCION_PRESCRIPCION`
    FOREIGN KEY (`idPrescripcion`)
    REFERENCES `SIREFA`.`Prescripcion` (`idPrescripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIREFA`.`Diagnostico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIREFA`.`Diagnostico`;
CREATE TABLE IF NOT EXISTS `SIREFA`.`Diagnostico` (
  `idDiagnostico` INT NOT NULL AUTO_INCREMENT,
  `idCita` INT NOT NULL,
  PRIMARY KEY (`idDiagnostico`),
  INDEX `FK_Cita_idx` (`idCita` ASC),
  CONSTRAINT `FK_DIAGNOSTICO_CITA`
    FOREIGN KEY (`idCita`)
    REFERENCES `SIREFA`.`Cita` (`idCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIREFA`.`Enfermedades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIREFA`.`Enfermedades`;
CREATE TABLE IF NOT EXISTS `SIREFA`.`Enfermedades` (
  ` idEnfermedad` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (` idEnfermedad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIREFA`.`Enfermedades_Diagnostico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIREFA`.`Enfermedades_Diagnostico`;
CREATE TABLE IF NOT EXISTS `SIREFA`.`Enfermedades_Diagnostico` (
  `idEnfermedad` INT NOT NULL,
  `idDiagnostico` INT NOT NULL,
  PRIMARY KEY (`idEnfermedad`, `idDiagnostico`),
  INDEX `FK_Enfermedad_idx` (`idEnfermedad` ASC),
  INDEX `FK_Diagnostico_idx` (`idDiagnostico` ASC),
  CONSTRAINT `FK_Enfermedad`
    FOREIGN KEY (`idEnfermedad`)
    REFERENCES `SIREFA`.`Enfermedades` (` idEnfermedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Diagnostico`
    FOREIGN KEY (`idDiagnostico`)
    REFERENCES `SIREFA`.`Diagnostico` (`idDiagnostico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIREFA`.`Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIREFA`.`Roles`;
CREATE TABLE IF NOT EXISTS `SIREFA`.`Roles` (
  `idRol` INT NOT NULL  AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIREFA`.`Privilegios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIREFA`.`Privilegios`;
CREATE TABLE IF NOT EXISTS `SIREFA`.`Privilegios` (
  `idPrivilegio` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idPrivilegio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIREFA`.`Roles_Privilegios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIREFA`.`Roles_Privilegios`;
CREATE TABLE IF NOT EXISTS `SIREFA`.`Roles_Privilegios` (
  `idRol` INT NOT NULL,
  `idPrivilegio` INT NOT NULL,
  PRIMARY KEY (`idRol`, `idPrivilegio`),
  INDEX `FK_ROL_idx` (`idRol` ASC),
  INDEX `FK_PRIVILEGIO_idx` (`idPrivilegio` ASC),
  CONSTRAINT `FK_ROL`
    FOREIGN KEY (`idRol`)
    REFERENCES `SIREFA`.`Roles` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PRIVILEGIO`
    FOREIGN KEY (`idPrivilegio`)
    REFERENCES `SIREFA`.`Privilegios` (`idPrivilegio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIREFA`.`Roles_Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIREFA`.`Roles_Usuarios`;
CREATE TABLE IF NOT EXISTS `SIREFA`.`Roles_Usuarios` (
  `idRol` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idRol`, `idUsuario`),
  INDEX `FK_USUARIO_idx` (`idUsuario` ASC),
  INDEX `FK_ROL_idx` (`idRol` ASC),
  CONSTRAINT `FK_ROLES_USUARIOS_USUARIO`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `SIREFA`.`Empleado` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ROLES_USUARIOS_ROLES`
    FOREIGN KEY (`idRol`)
    REFERENCES `SIREFA`.`Roles` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
