/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dialogPackageLuis;

import classdbpackage.RolDB;
import classpackage.Empleado;
import classpackage.Roles;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis Manuel
 */
public class dlgOtorgarRoles extends javax.swing.JDialog {

    
    private ArrayList<Roles> listaDeRolesExistentes;
    private ArrayList<Roles> listaDeRolesNuevos; //Roles que se les ha asignado al usuario
    private ArrayList<Roles> listaDeRolesEliminados; //Role que se le han eliminado al usuario
    private Empleado empleado;
    private RolDB rolDB;
    /**
     * Creates new form dlgOtorgarRoles
     */
    public dlgOtorgarRoles(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
        
        this.empleado = new Empleado();
        this.rolDB = new RolDB();
        
        this.listaDeRolesExistentes = new  ArrayList<Roles>();
        this.listaDeRolesNuevos = new  ArrayList<Roles>();
        this.listaDeRolesEliminados = new  ArrayList<Roles>();
                
    }
    
    public dlgOtorgarRoles(java.awt.Frame parent, boolean modal, Empleado empleado) 
    {
        super(parent, modal);
        initComponents();
        
        this.empleado = empleado;
        this.rolDB = new RolDB(this.empleado);
        
        this.listaDeRolesExistentes = new  ArrayList<Roles>();
        this.listaDeRolesNuevos = new  ArrayList<Roles>();
        this.listaDeRolesEliminados = new  ArrayList<Roles>();        
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listBoxRolesExistentes = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listBoxRolesUsuario = new javax.swing.JList();
        btnAgregarRol = new javax.swing.JButton();
        btnEliminarRol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Otorgar roles a usuario"));

        listBoxRolesExistentes.setBorder(javax.swing.BorderFactory.createTitledBorder("Roles existentes"));
        jScrollPane1.setViewportView(listBoxRolesExistentes);

        listBoxRolesUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Roles actuales de usuario"));
        listBoxRolesUsuario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listBoxRolesUsuario);

        btnAgregarRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/arrow_right.png"))); // NOI18N
        btnAgregarRol.setText("Agregar rol");
        btnAgregarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRolActionPerformed(evt);
            }
        });

        btnEliminarRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/arrow_left.png"))); // NOI18N
        btnEliminarRol.setText("Eliminar rol");
        btnEliminarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarRolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarRol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarRol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnAgregarRol)
                        .addGap(48, 48, 48)
                        .addComponent(btnEliminarRol))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.cargarRoles();
        this.cargarRolesDeUsuario();
    }//GEN-LAST:event_formWindowOpened

    private void btnAgregarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRolActionPerformed
        
        Roles rolSeleccionado = (Roles)this.listBoxRolesExistentes.getSelectedValue();
        String mensajeError = null;
        
        if(rolSeleccionado != null)
        {
            mensajeError = this.empleado.getEmpleadoDB().asignarRol(rolSeleccionado);
            
            if(mensajeError == null)
            {
                JOptionPane.showMessageDialog(this, "Se ha asignado el rol exitosamente", "Otorgar roles a usuario", JOptionPane.INFORMATION_MESSAGE);
                this.cargarRolesDeUsuario();
            }
            else
            {
                JOptionPane.showMessageDialog(this, mensajeError, "Otorgar roles a usuario", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Seleccione un rol", "Otorgar roles a usuario", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnAgregarRolActionPerformed

    private void btnEliminarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarRolActionPerformed
        
        Roles rolSeleccionado = (Roles)this.listBoxRolesUsuario.getSelectedValue();
        String mensajeError = null;
        
        if(rolSeleccionado != null)
        {
            mensajeError = this.empleado.getEmpleadoDB().eliminarRol(rolSeleccionado);
            
            if(mensajeError == null)
            {
                if(JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar este rol del usuario?", "Eliminar rol", JOptionPane.YES_NO_OPTION) == 0)
                {
                    JOptionPane.showMessageDialog(this, "Se ha eliminado el rol exitosamente", "Otorgar roles a usuario", JOptionPane.INFORMATION_MESSAGE);
                    this.cargarRolesDeUsuario();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, mensajeError, "Otorgar roles a usuario", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Seleccione un rol", "Otorgar roles a usuario", JOptionPane.WARNING_MESSAGE);
        }        
    }//GEN-LAST:event_btnEliminarRolActionPerformed

    private void cargarRoles()
    {
        this.listaDeRolesExistentes = this.rolDB.obtenerRoles();
        this.listBoxRolesExistentes.setListData(this.listaDeRolesExistentes.toArray());
    }
    
    private void cargarRolesDeUsuario()    
    {
        ArrayList<Roles> listaDeRolesDeUsuario = this.empleado.getEmpleadoDB().obtenerRoles();
        this.listBoxRolesUsuario.setListData(listaDeRolesDeUsuario.toArray());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgOtorgarRoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgOtorgarRoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgOtorgarRoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgOtorgarRoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgOtorgarRoles dialog = new dlgOtorgarRoles(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarRol;
    private javax.swing.JButton btnEliminarRol;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listBoxRolesExistentes;
    private javax.swing.JList listBoxRolesUsuario;
    // End of variables declaration//GEN-END:variables
}
